/**
 * Created by ajmul on 2/9/2017.
 */
//Function to define the master columns array to be used by the slickgrid

function defineCols(){
    var columns1 = [{id: "tm_name", name:"Team Manager", field:"tm_name", sortable: true, sorter:sorterStringCompare},
        {id: "CO_name_com", name:"Case Owner", field:"CO_name_com", sortable: true, sorter:sorterStringCompare},
        {id: "EventId", name:"Claim Number", field:"EventId", sortable: true, sorter:sorterNumeric},
        {id: "Claim_rating", name:"Claim rating", field:"Claim_rating", sortable: true, sorter:sorterStringCompare},
        {id: "ECO_min", name:"Min duration", field:"ECO_min"},
        {id: "ECO_opt", name:"Optimum duration", field:"ECO_opt"},
        {id: "change_ECO_opt", name:"Opt Changed", field:"change_ECO_opt"},
        {id: "ECO_max", name:"Max duration", field:"ECO_max"},
        {id: "wcdays", name:"WC days actually paid", field:"wcdays"},
        {id: "WC_to", name:"WC to Date", field:"WC_to"},
        {id: "Next_KPI", name:"Next KPI", field:"Next_KPI"},
        {id: "Next_KPI_crossing_date", name:"Next KPI Crossing Date", field:"Next_KPI_crossing_date"},
        {id: "next_monitor_task_date", name:"Next Monitor Task Date", field:"next_monitor_task_date"},
        {id: "Accident_date", name:"Accident Date", field:"Accident_date"},
        {id: "IRP_required", name:"IRP Required Date", field:"IRP_required"},
        {id: "IRP_expiry_date", name:"IRP expiry date", field:"IRP_expiry_date"},
        {id: "taxi_expiry", name:"Taxi Expiry", field:"taxi_expiry"},
        {id: "RTW_TARGETDATE", name:"RTW date", field:"RTW_TARGETDATE"},
        {id: "RTW_RESULTRATIONAL", name:"Result Rationale", field:"RTW_RESULTRATIONAL"},
        {id: "allocation_date", name:"Allocation Date", field:"allocation_date"},
        {id: "ACC012_creationdate_date", name:"Last ACC012 Creation Date", field:"ACC012_creationdate_date"},
        {id: "ACC012_status", name:"Last ACC012 Status", field:"ACC012_status"},
        {id: "IncapToDate", name:"Medical Incap to Date", field:"IncapToDate"},
        {id: "approved_incap_to", name:"Approved Incap To Date", field:"approved_incap_to"},
        {id: "incap_duration", name:"Incap Duration", field:"incap_duration"},
        {id: "IncapTypeCode", name:"Incap Type", field:"IncapTypeCode"},
        {id: "Form", name:"Form", field:"Form"},
        {id: "MFPContactNameDefault", name:"Provider On Med Cert", field:"MFPContactNameDefault"},
        {id: "WC_Entitle_summary", name:"Last WC Entitlement Summary", field:"WC_Entitle_summary"},
        {id: "WC_Entitlement_status", name:"Last WC Entitlement Status", field:"WC_Entitlement_status"},
        {id: "warning", name:"Alerts", field:"warning"},
        {id: "VRS_new", name:"Recent VRS services", field:"VRS_new"},
        {id: "VendorName", name:"Vendor Name", field:"VendorName"},
        {id: "HCS_POAmountGross", name:"HCSS/HBNR Amount", field:"HCS_POAmountGross"},
        {id: "HCS_POQuantityApproved", name:"HCSS/HBNR Quantity Approved", field:"HCS_POQuantityApproved"},
        {id: "HCS_POServiceDuration", name:"HCSS/HBNR Duration (days)", field:"HCS_POServiceDuration"},
        {id: "HCS_POServiceTo", name:"HCSS/HBNR To Date", field:"HCS_POServiceTo"},
        {id: "IR_POAmountGross", name:"IR Amount", field:"IR_POAmountGross"},
        {id: "IR_POServiceDuration", name:"IR duration (days)", field:"IR_POServiceDuration"},
        {id: "IR_POServiceTo", name:"IR To Date", field:"IR_POServiceTo"},
        {id: "eq_amount", name:"Equipment Amount", field:"eq_amount"},
        {id: "IRA_amount", name:"IRA Amount", field:"IRA_amount"},
        {id: "age", name:"Age", field:"age", sortable: true, formatter: intFormatter, sorter:sorterNumeric},
        {id: "change_diag", name:"Diag Changed", field:"change_diag"},
        {id: "ms_diag_desc", name:"Diagnosis", field:"ms_diag_desc"},
        {id: "wt_occu", name:"Occupation", field:"wt_occu"},
        {id: "Occupationdesc", name:"Occupation Without Worktype", field:"Occupationdesc"},
        {id: "STAGE", name:"SCU Stage", field:"STAGE"},
        {id: "scu_ddd", name:"SCU Cover Decision Due Date", field:"scu_ddd"},
        {id: "last_paydate", name:"Last SCU Payment Date", field:"last_paydate"},
        {id: "IBSC_task_date", name:"IBSC Task Target Date", field:"IBSC_task_date"},
        {id: "RPC_comp_date3", name:"RPC Due Date", field:"RPC_comp_date3"},
        {id: "EmplType_word", name:"Employment Type", field:"EmplType_word"},
        {id: "WClast", name:"Last WC Paid Date", field:"WClast"},
        {id: "weeks_til_close", name:"Weeks Until WC Outcome", field:"weeks_til_close"},
        {id: "RPC_comp_date2", name:"RPC sorting column", field:"RPC_comp_date2"},
        {id: "vulnerable", name:"Vulnerable Client", field:"vulnerable",sortable: true, sorter:sorterStringCompare},
        {id: "imprison_ind", name:"Imprisonment Indicator", field:"imprison_ind",sortable: true, sorter:sorterStringCompare},
        {id: "care_ind", name:"Care Indicator", field:"care_ind",sortable: true, sorter:sorterStringCompare},
        {id: "ap_lastupdatedate", name:"Action Plan Last Update", field:"ap_lastupdatedate"},
        {id: "ap_CLIENTREVIEWDATE", name:"Action Plan Review Date", field:"ap_CLIENTREVIEWDATE"},
        {id: "Portfolio_Comment", name: "Portfolio Comment", field:"Portfolio_Comment", sortable: true, sorter:sorterStringCompare},
        {id: "Rehab_Comment", name:"Rehab Comment", field:"Rehab_Comment", sortable: true, sorter:sorterStringCompare},
        {id: "Training_Comment", name:"Training Comment", field:"Training_Comment", sortable: true, sorter:sorterStringCompare},
        {id: "Colour", name: "Colour", field:"Colour", sortable: true, sorter:sorterStringCompare},
        {id: "PC_Date_Saved", name:"Portfolio Comment Saved Date", field:"PC_Date_Saved"},
        {id: "Date_Saved", name:"Date Saved", field:"Date_Saved"},
        {id: "Rehab_Advice_Date", name:"Rehab Advice Date", field:"Rehab_Advice_Date"},
        {id: "RIS_Stream", name:"RIS Stream", field:"RIS_Stream"},
        {id: "Revisit_Date", name:"Revisit Date", field:"Revisit_Date"},
        {id: "Flag", name:"Flag", field:"Flag"},
        {id: "Job_Status", name:"Job Status", field:"Job_Status"},
        {id: "Vulnerable_Client", name:"Vulnerable Client", field:"Vulnerable_Client"},
        {id: "Reason_For_React", name:"Reason for Reactivation", field:"Reason_For_React"},
        {id: "TM_Rehab", name:"TM Rehab", field:"TM_Rehab"},
        {id: "Rehab_Summary", name:"Rehab Summary", field:"Rehab_Summary"},
        {id: "Rehab_Revisit_Date", name:"Rehab Revisit Date", field:"Rehab_Revisit_Date"}
    ];

    return columns1;


}